### ISSUE TITLE
Issue on page /tutorials/rv.html

### ISSUE THREAD

**Issue by Richardjmorton** [exoplanet-dev/case-studies#40]
Hi, I have been reading the excellent case studies using exoplanet in order to figure out some issues with my own problems. One thing that has been bugging me, and is present in your examples, is the reparameterisations of variables. 

For example, in the exoplanet examples, often the prior is specified for the log of a parameter. However there is no line that incorporates the jacobian for this change of variables, i.e. through pm.Potential.

Should the jacobian be present, or is not required in these cases?

**Comment by dfm** [comment]
Whether or not you want to include the Jacobian would depend on what prior you're targeting. I would normally actually prefer a logarithmic prior (like the ones you're referring to) for any parameter with units, so the lack of a Jacobian here is intentional. If you wanted to specify your prior in linear space, I'd recommend just using the linear parameter directly, rather than explicitly including a Jacobian. Hope this helps!

**Comment by Richardjmorton** [comment]
Thanks for responding! Having spent some time thinking about what you said, I think I finally get why/when the Jacobian needs to be included.
